export type FAQ = { question: string; answer: string };
export type Service = {
  slug: string; name: string; short: string; intro: string; signs: string[]; benefits: string[];
  image: string; imageAlt: string; emergency?: boolean; faqs: FAQ[];
};

const standardFaqs = (name: string): FAQ[] => [
  { question: `Do you provide ${name.toLowerCase()} for homes and businesses?`, answer: `Yes. CTA Plumbing 100 serves homeowners, property managers, contractors, and commercial customers across the Treasure Valley. Contact us to discuss the property and scope of work.` },
  { question: "How do I request an estimate?", answer: "Call or send a service request with the property location and a short description. We will follow up to clarify the work and discuss scheduling." },
  { question: "What areas do you serve?", answer: "We serve Nampa, Boise, Meridian, Caldwell, Eagle, Kuna, Star, Middleton, and surrounding Treasure Valley communities." },
];

const make = (slug: string, name: string, short: string, intro: string, signs: string[], benefits: string[], image = "/images/technician-service.webp", emergency = false): Service => ({ slug, name, short, intro, signs, benefits, image, imageAlt: `${name} service performed by a CTA Plumbing 100 technician`, emergency, faqs: standardFaqs(name) });

export const services: Service[] = [
  make("commercial-plumbing", "Commercial Plumbing", "Responsive plumbing support for commercial spaces, facilities, and projects.", "Commercial plumbing needs clear coordination and work that respects operating schedules. We help Treasure Valley businesses address repairs, fixture needs, piping, and project plumbing with straightforward communication.", ["Recurring plumbing disruptions", "Fixture or supply line problems", "Plumbing needs during a tenant improvement", "Drain or water heating concerns"], ["Clear project communication", "Support for occupied properties", "Solutions matched to the facility"], "/images/commercial-team.webp"),
  make("water-heaters", "Water Heater Services", "Water heater troubleshooting, repair, replacement, and installation.", "When hot water becomes unreliable, we help identify the cause and explain practical repair or replacement options for conventional and tankless systems.", ["No hot water", "Water takes too long to heat", "Leaking near the unit", "Unusual noise or discolored water"], ["More dependable hot water", "Equipment sized for the property", "Clear repair or replacement guidance"], "/images/water-heater.webp", true),
  make("sewer-drain-cleaning", "Sewer & Drain Cleaning", "Clear slow, clogged, or backed up drains and investigate recurring trouble.", "A slow drain may be local to one fixture or point to a larger sewer line issue. We assess the symptoms before recommending the right cleaning or next diagnostic step.", ["Slow tubs, sinks, or showers", "Gurgling fixtures", "Repeated clogs", "Water backing up through a drain"], ["Restore drainage", "Reduce repeat blockages", "Identify signs of a larger sewer problem"], "/images/drain-cleaning.webp", true),
  make("repiping", "Whole Home Repiping", "Replace aging or problem piping with a coordinated repiping plan.", "Frequent leaks, poor flow, or deteriorating materials can make repeated spot repairs less practical. We help evaluate whether a partial or whole property repipe fits the situation.", ["Frequent pipe leaks", "Low or inconsistent pressure", "Discolored water", "Known aging supply piping"], ["A coordinated piping solution", "Improved reliability", "Planning that considers access and disruption"], "/images/pipe-repair.webp"),
  make("pipe-leak-repair", "Pipe & Leak Repair", "Find and repair leaking, damaged, frozen, or failed plumbing lines.", "Water where it should not be can damage finishes and interrupt daily routines. We trace the likely source, explain access needs, and recommend an appropriate repair.", ["Wet cabinets or walls", "Unexpected water use", "Stains or musty odors", "Loss of pressure or visible pipe damage"], ["Limit ongoing water damage", "Address the source and not only the symptom", "Repair options explained clearly"], "/images/technician-service.webp", true),
  make("fixtures-faucets", "Plumbing Fixtures & Faucets", "Repair and install faucets, sinks, valves, and everyday plumbing fixtures.", "Fixtures affect how a kitchen, bath, or commercial space works every day. We handle leaks, worn parts, replacements, and installation of fixtures selected by the owner.", ["Dripping faucet", "Loose or difficult handles", "Low flow at one fixture", "A planned fixture upgrade"], ["Stop nuisance leaks", "Improve everyday function", "Professional connections and testing"], "/images/kitchen-faucet.webp"),
  make("bathroom-plumbing", "Bathroom Plumbing", "Practical plumbing solutions for showers, tubs, sinks, toilets, and remodels.", "From persistent leaks to a reconfigured bathroom, we help keep the plumbing behind your most used spaces dependable and serviceable.", ["Slow bathroom drains", "Leaking shower or tub valve", "Fixture replacement", "Bathroom layout changes"], ["Coordinated fixture service", "Better function and water control", "Support for repairs and remodels"], "/images/bathroom.webp"),
  make("kitchen-plumbing", "Kitchen Plumbing", "Service for sinks, faucets, disposals, supply lines, drains, and remodel plumbing.", "Kitchen plumbing needs to work around cabinetry, appliances, and daily use. We address common failures and coordinate plumbing changes for upgrades.", ["Sink or faucet leak", "Slow kitchen drain", "Disposal trouble", "New sink or appliance connection"], ["Restore a frequently used workspace", "Coordinate connected fixtures", "Clean, thoughtful installation"], "/images/kitchen-faucet.webp"),
  make("toilets", "Toilet Repair & Installation", "Resolve running, leaking, rocking, clogged, or outdated toilets.", "A toilet problem can waste water or quickly become disruptive. We inspect the fixture and connection, then explain whether repair or replacement is the better fit.", ["Constant running", "Leak at the base", "Weak or incomplete flush", "Frequent clogging"], ["Reliable flushing", "Correct sealing and connection", "Repair or replacement options"], "/images/bathroom.webp", true),
  make("garbage-disposals", "Garbage Disposal Services", "Diagnose, repair, replace, or install kitchen garbage disposals.", "If a disposal hums, leaks, jams, or will not run, we can evaluate the unit and related sink connections before recommending the next step.", ["Humming or no operation", "Leak below the sink", "Persistent odors", "Slow drainage around the disposal"], ["Restore kitchen convenience", "Check related drain connections", "Appropriate unit replacement when needed"], "/images/kitchen-faucet.webp"),
  make("sump-pumps", "Sump Pump Services", "Inspection, repair, replacement, and installation for sump pump systems.", "A sump pump is easy to overlook until water threatens the property. We help assess pump condition, discharge routing, and replacement needs.", ["Pump will not start", "Unusual cycling or noise", "Visible pit or discharge issues", "Concern before wet weather"], ["Improve readiness for water events", "Verify basic system operation", "Replace unreliable equipment"], "/images/pipe-repair.webp", true),
  make("sewer-line-repair", "Sewer Line Repair", "Assess and repair damaged sewer piping serving Treasure Valley properties.", "Recurring backups, odors, or soggy areas can point to a damaged building sewer. We help identify the next diagnostic or repair step and explain the work involved.", ["Repeated backups throughout the property", "Sewer odor", "Unexplained soft or wet ground", "Multiple drains affected at once"], ["Address underlying line damage", "Clear repair planning", "Coordination with excavation when needed"], "/images/excavation.webp", true),
  make("excavation", "Plumbing Excavation", "Targeted excavation for underground water and sewer plumbing work.", "Some underground plumbing repairs require safe access to buried piping. We coordinate excavation around the plumbing objective and keep the work area organized.", ["Confirmed underground pipe failure", "Water surfacing outdoors", "Sewer line replacement needs", "New underground plumbing route"], ["Direct access to buried piping", "Coordinated plumbing and excavation", "A defined repair scope"], "/images/excavation.webp"),
  make("backflow-prevention", "Backflow Prevention", "Backflow device service and installation for applicable plumbing systems.", "Backflow prevention helps protect potable water from unwanted reverse flow. We can discuss device service, replacement, and installation needs for residential or commercial properties.", ["Existing device leaks", "A device is due for service", "Property improvements require protection", "Commercial system changes"], ["Support water supply protection", "Correct device installation", "Solutions matched to the plumbing system"]),
  make("water-filtration", "Water Filtration Systems", "Improve water quality at a fixture or across the property.", "Filtration needs vary with water concerns and household or facility use. We help plan and install practical equipment for one fixture or the whole property.", ["Taste or odor concerns", "Sediment at fixtures", "A desired drinking water upgrade", "Interest in filtration for the whole property"], ["Equipment matched to the goal", "Professional plumbing connections", "Convenient filtered water"], "/images/water-system.webp"),
  make("water-softeners", "Water Softener Services", "Water softener installation, replacement, and plumbing connections.", "Hard water scale can affect fixtures and cleaning. We help connect, replace, or plan a softening system suited to the property and available space.", ["Scale on fixtures", "Existing softener no longer performs", "Concerns about how the water feels", "Planning a new softener"], ["Reduce scale related to hardness", "Protect connected fixtures", "Organized equipment installation"], "/images/water-system.webp"),
  make("gas-lines", "Gas Line Services", "Gas piping evaluation, repair, and installation for applicable appliances and projects.", "Gas line work demands careful planning. Contact us to discuss a suspected issue, new appliance connection, or project piping need. If you smell gas, leave the area and contact your gas utility or emergency services first.", ["Suspected gas odor", "New gas appliance", "Damaged or altered piping", "Remodel or equipment project"], ["Careful project planning", "Piping matched to the intended use", "Clear guidance focused on safety"], "/images/commercial-team.webp", true),
  make("plumbing-remodels", "Plumbing Remodels", "Coordinate plumbing changes for kitchens, bathrooms, and commercial improvements.", "Remodel plumbing works best when initial pipe locations, fixture choices, access, and project sequencing are aligned early. We support contractors and property owners from planning through fixture connection.", ["Moving a sink, shower, or toilet", "Adding plumbing fixtures", "Updating outdated piping during a remodel", "Commercial tenant improvements"], ["Better trade coordination", "Plumbing planned around the finished space", "Support from initial piping through final fixture work"], "/images/customer-consultation.webp"),
  make("general-repairs", "General Plumbing Repairs", "Straightforward help for common residential and commercial plumbing problems.", "Not every plumbing issue fits a neat category. Tell us what you see, hear, or smell, and we will help determine the appropriate next step.", ["Unidentified leak or noise", "A valve will not operate", "One fixture is not working correctly", "General plumbing concern"], ["One place to start", "Clear explanation of findings", "Repair recommendations based on the problem"]),
  make("emergency-plumbing", "Emergency Plumbing", "24/7 help for serious leaks, backups, overflows, and plumbing failures.", "When a plumbing problem threatens property or essential service, call CTA Plumbing 100 for 24/7 emergency plumbing help across the Treasure Valley.", ["Burst or badly leaking pipe", "Sewer backup", "Overflow that cannot be stopped", "Water heater failure or flooding caused by plumbing"], ["Emergency help available 24/7", "Fast guidance for the first steps", "Focused response to urgent property risk"], "/images/emergency.webp", true),
];

export const serviceMap = Object.fromEntries(services.map((service) => [service.slug, service]));

export type Location = { slug: string; city: string; title: string; intro: string; local: string; faqs: FAQ[] };
const cityData = [
  ["boise", "Boise", "Plumber in Boise, Idaho", "Boise properties range from established neighborhoods to active commercial corridors. CTA Plumbing 100 provides practical plumbing support that fits occupied homes, managed properties, and business spaces.", "We travel throughout Boise and connect customers with repair, water heating, drain, fixture, and project plumbing services."],
  ["meridian", "Meridian", "Plumber in Meridian, Idaho", "Meridian continues to grow, and its plumbing needs include both everyday repairs and systems supporting newer homes and expanding businesses.", "Our team serves Meridian customers with clear scheduling communication and solutions for kitchens, bathrooms, water heaters, piping, drains, and remodels."],
  ["nampa", "Nampa", "Plumbing Services in Nampa, Idaho", "CTA Plumbing 100 is proud to make Nampa a central part of our Treasure Valley service area. We help local homeowners, property managers, contractors, and businesses keep plumbing systems working as they should.", "From established Nampa neighborhoods to new construction and commercial properties, we provide repair, replacement, drain, water heating, and project plumbing support."],
  ["caldwell", "Caldwell", "Plumber in Caldwell, Idaho", "Caldwell customers need plumbing service that accounts for varied property ages, rural edges, and active community growth.", "We serve Caldwell with general repairs, drain cleaning, water heater work, fixtures, piping, sewer concerns, and other residential or commercial plumbing needs."],
  ["eagle", "Eagle", "Plumber in Eagle, Idaho", "Thoughtful workmanship and respect for finished spaces matter in Eagle homes and businesses. We approach plumbing repairs and improvements with careful communication.", "CTA Plumbing 100 supports Eagle properties with leak repair, fixture work, water systems, remodel plumbing, drains, and larger piping projects."],
  ["kuna", "Kuna", "Plumber in Kuna, Idaho", "As Kuna grows, dependable plumbing supports both existing properties and newly finished spaces. We help customers move from symptoms to a clear next step.", "Our Kuna services cover common repairs, water heaters, drains, fixtures, repiping, kitchen and bathroom plumbing, and commercial needs."],
  ["star", "Star", "Plumber in Star, Idaho", "Star combines rapid residential growth with established local properties. CTA Plumbing 100 provides flexible plumbing support for repairs, upgrades, and projects.", "We help customers in Star with water and drain piping, fixtures, water heaters, softeners, filtration, remodels, and urgent plumbing concerns."],
  ["middleton", "Middleton", "Plumber in Middleton, Idaho", "Middleton property owners deserve a straightforward way to address plumbing trouble and plan improvements without unnecessary confusion.", "CTA Plumbing 100 travels to Middleton for residential and commercial repairs, drain and sewer needs, water systems, fixtures, and plumbing project work."],
] as const;

export const locations: Location[] = cityData.map(([slug, city, title, intro, local]) => ({ slug, city, title, intro, local, faqs: [
  { question: `Does CTA Plumbing 100 serve all of ${city}?`, answer: `We serve customers throughout ${city} and nearby Treasure Valley communities. Contact us with your service address to confirm scheduling and availability.` },
  { question: `What plumbing services are available in ${city}?`, answer: `We handle general repairs, leaks, drains, water heaters, fixtures, piping, remodel plumbing, and commercial work. We also provide 24/7 emergency plumbing for urgent needs.` },
  { question: `How can I request plumbing service in ${city}?`, answer: "Call us or complete the online request form. Include the property location and a short description so we can follow up efficiently." },
] }));
export const locationMap = Object.fromEntries(locations.map((location) => [location.slug, location]));
