import type { Metadata } from "next";
import Link from "next/link";
import { notFound } from "next/navigation";
import { ArrowRight, CheckCircle2 } from "lucide-react";
import { locationMap, locations, services } from "@/lib/content";
import { site } from "@/lib/site";
import { Breadcrumbs, CallNow, FinalCTA, SectionHeading } from "@/components/shared";
import { FAQList } from "@/components/faq";
import { Button } from "@/components/ui/button";
import { JsonLd } from "@/components/json-ld";
type Props={params:Promise<{slug:string}>};
export function generateStaticParams(){return locations.map((location)=>({slug:location.slug}))}
export async function generateMetadata({params}:Props):Promise<Metadata>{const {slug}=await params;const location=locationMap[slug];if(!location)return{};return{title:location.title,description:`CTA Plumbing 100 provides residential and commercial plumbing services in ${location.city}, Idaho and nearby Treasure Valley communities.`,alternates:{canonical:`/service-areas/${slug}`}}}
export default async function LocationPage({params}:Props){const {slug}=await params;const location=locationMap[slug];if(!location)notFound();const schema=[{"@context":"https://schema.org","@type":"Service",name:`Plumbing services in ${location.city}, Idaho`,provider:{"@id":`${site.url}/#business`},areaServed:{"@type":"City",name:`${location.city}, Idaho`},url:`${site.url}/service-areas/${location.slug}`},{"@context":"https://schema.org","@type":"FAQPage",mainEntity:location.faqs.map((faq)=>({"@type":"Question",name:faq.question,acceptedAnswer:{"@type":"Answer",text:faq.answer}}))},{"@context":"https://schema.org","@type":"BreadcrumbList",itemListElement:[{"@type":"ListItem",position:1,name:"Home",item:site.url},{"@type":"ListItem",position:2,name:"Service Areas",item:`${site.url}/service-areas`},{"@type":"ListItem",position:3,name:location.city,item:`${site.url}/service-areas/${location.slug}`}]}];return <><JsonLd data={schema}/><div className="page-hero"><Breadcrumbs items={[{label:"Service Areas",href:"/service-areas"},{label:location.city}]}/><div className="container relative z-10 max-w-4xl py-16 sm:py-24"><p className="eyebrow !text-copper-light">Treasure Valley service area</p><h1 className="font-display text-5xl font-black tracking-tight sm:text-6xl">{location.title}</h1><p className="mt-6 max-w-2xl text-lg leading-8 text-slate-300">{location.intro}</p><div className="mt-8 flex flex-wrap gap-3"><CallNow/><Button variant="outline" size="lg" asChild><Link href="/contact">Request Service</Link></Button></div></div></div><section className="py-20"><div className="container grid items-start gap-12 lg:grid-cols-[1.1fr_.9fr]"><div><SectionHeading eyebrow={`Serving ${location.city}`} title={`Local plumbing support for ${location.city} properties.`} text={location.local}/><p className="section-copy">Every request begins with the property, symptoms, and intended outcome. We avoid generic claims and help residential or commercial customers understand the appropriate next step.</p></div><aside className="rounded-2xl bg-slate-50 p-7"><h2 className="text-2xl font-black text-navy">Frequently requested services</h2><ul className="mt-6 grid gap-3">{services.slice(0,6).map((service)=><li key={service.slug}><Link className="flex items-center gap-3 rounded-lg bg-white p-3 font-bold text-navy hover:text-copper-dark" href={`/services/${service.slug}`}><CheckCircle2 className="size-5 text-copper-dark"/>{service.name}<ArrowRight className="ml-auto size-4"/></Link></li>)}</ul></aside></div></section><section className="bg-slate-50 py-20"><div className="container max-w-4xl"><SectionHeading center eyebrow={`${location.city} plumbing questions`} title="Helpful answers before requesting service."/><FAQList items={location.faqs}/></div></section><FinalCTA/></>}
