import type { Metadata } from "next";
import Link from "next/link";
import { CheckCircle2 } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Breadcrumbs, FinalCTA, SectionHeading, SplitImage } from "@/components/shared";

export const metadata: Metadata = { title: "About Us", description: "Learn about CTA Plumbing 100 and our straightforward approach to residential and commercial plumbing across Idaho’s Treasure Valley.", alternates: { canonical: "/about" } };
const values = ["Workmanship focused on quality", "Honest, useful communication", "Reliable scheduling updates", "Respect for homes and business spaces", "Residential and commercial capability", "A local Treasure Valley focus"];
export default function AboutPage() { return <><div className="page-hero"><Breadcrumbs items={[{ label: "About Us" }]} /><div className="container relative z-10 max-w-4xl py-16 sm:py-24"><p className="eyebrow !text-copper-light">About CTA Plumbing 100</p><h1 className="font-display text-5xl font-black tracking-tight sm:text-6xl">Straightforward plumbing service, rooted in the Treasure Valley.</h1><p className="mt-6 max-w-2xl text-lg leading-8 text-slate-300">We help homeowners, property managers, contractors, and businesses move plumbing needs from uncertainty to a practical next step.</p></div></div><section className="py-20"><SplitImage src="/images/team-van.webp" alt="CTA Plumbing 100 team beside a branded service vehicle" reverse><SectionHeading eyebrow="Our commitment" title="The way plumbing service should feel." text="CTA Plumbing 100 is built around dependable work and respectful communication. Whether the request is a familiar household repair or coordinated commercial work, we aim to make the process understandable." /><ul className="prose-list mt-6 grid gap-3 sm:grid-cols-2">{values.map((value) => <li key={value}>{value}</li>)}</ul><Button className="mt-8" asChild><Link href="/contact">Request Service</Link></Button></SplitImage></section><section className="bg-slate-50 py-20"><div className="container"><SectionHeading center eyebrow="Who we serve" title="Plumbing support for the people responsible for a property." /><div className="grid gap-5 md:grid-cols-3">{[["Homeowners","Repairs and improvements handled with care for occupied spaces."],["Property professionals","Clear communication for managed properties and ongoing needs."],["Businesses & contractors","Commercial repairs and project plumbing coordinated around the work."]].map(([title,text]) => <article className="card" key={title}><CheckCircle2 className="text-copper-dark" /><h2 className="mt-5 text-xl font-black text-navy">{title}</h2><p className="mt-3 leading-7 text-slate-600">{text}</p></article>)}</div></div></section><FinalCTA /></> }
