import type { Metadata } from "next";
import { AlertTriangle } from "lucide-react";
import { Breadcrumbs, CallNow, SectionHeading } from "@/components/shared";
import { LeadForm } from "@/components/lead-form";
import { JsonLd } from "@/components/json-ld";
import { site } from "@/lib/site";
export const metadata: Metadata = { title: "24/7 Emergency Plumber in the Treasure Valley", description: "Call CTA Plumbing 100 for 24/7 emergency plumbing in Nampa, Boise, Meridian, and across the Treasure Valley.", alternates: { canonical: "/emergency-plumbing" } };
const emergencies=["Burst pipes","Major or uncontrolled leaks","Overflowing toilets","Sewer backups","Water heater failures","Gas line concerns","Flooding caused by plumbing","Loss of water service","Severely backed up drains"];
export default function EmergencyPage(){const schema={"@context":"https://schema.org","@type":"Service",name:"24/7 Emergency Plumbing",description:"Emergency plumbing for serious leaks, burst pipes, sewer backups, overflows, and urgent plumbing failures.",provider:{"@id":`${site.url}/#business`},areaServed:site.cities.map((city)=>`${city}, Idaho`),hoursAvailable:{"@type":"OpeningHoursSpecification",dayOfWeek:["Monday","Tuesday","Wednesday","Thursday","Friday","Saturday","Sunday"],opens:"00:00",closes:"23:59"},url:`${site.url}/emergency-plumbing`};return <><JsonLd data={schema}/><div className="bg-emergency text-white"><Breadcrumbs items={[{label:"Emergency Plumbing"}]}/><div className="container py-16 sm:py-24"><div className="max-w-4xl"><p className="mb-4 font-black uppercase tracking-[.2em] text-red-100">24/7 urgent plumbing help</p><h1 className="font-display text-5xl font-black tracking-tight sm:text-6xl">Emergency plumbing help day or night.</h1><p className="mt-6 max-w-2xl text-lg leading-8 text-red-50">CTA Plumbing 100 provides 24/7 emergency plumbing across the Treasure Valley. Call anytime for urgent plumbing problems. If there is immediate danger, leave the area and contact emergency services or the appropriate utility first.</p><div className="mt-8"><CallNow label="Call 24/7 Emergency Plumbing"/></div></div></div></div><section className="py-20"><div className="container grid gap-12 lg:grid-cols-2"><div><SectionHeading eyebrow="Common emergencies" title="Problems that should not wait for routine scheduling."/><ul className="grid gap-3 sm:grid-cols-2">{emergencies.map((item)=><li className="flex gap-3 rounded-xl bg-red-50 p-4 font-semibold text-navy" key={item}><AlertTriangle className="shrink-0 text-emergency"/>{item}</li>)}</ul><div className="mt-8 rounded-2xl bg-navy p-6 text-white"><h2 className="text-xl font-black">Before help arrives</h2><p className="mt-3 leading-7 text-slate-300">If it is safe, stop water at the nearest fixture valve or the property’s main shutoff. Avoid electrical hazards and contaminated backup water. For a suspected gas leak, leave the property immediately and contact the gas utility or emergency services.</p></div></div><div><h2 className="mb-5 text-3xl font-black text-navy">Emergency request form</h2><LeadForm emergency/></div></div></section></>}
