import type { Metadata } from "next";
import Image from "next/image";
import Link from "next/link";
import { ArrowDown, Check, Droplets, ExternalLink, Flame, MapPin, Phone, ShieldCheck, Star, Wrench } from "lucide-react";
import { EstimateForm } from "./estimate-form";
import { JsonLd } from "@/components/json-ld";
import { site } from "@/lib/site";

export const metadata:Metadata={title:"Free Plumbing Estimate in the Treasure Valley",description:"Request a free plumbing estimate from CTA Plumbing 100. Limited-time savings on water softener and water heater installation in Nampa and the Treasure Valley.",alternates:{canonical:"/estimate-a"},openGraph:{title:"Get a Free Plumbing Estimate | CTA Plumbing 100",description:"Limited-time installation offers and professional plumbing service across the Treasure Valley.",url:"/estimate-a",images:[{url:"/images/hero-plumber.webp",alt:"CTA Plumbing 100 technician serving a Treasure Valley home"}]}};
const emergencyHref="tel:2082470906";
const reviews=[
  {name:"Brittany Caylor",text:"Caden was great! He removed an old kitchen sink and faucet and replaced them with new ones, and it looks beautiful. He took his time to do it right and even went to the store to ensure he had the exact materials needed for proper and secure fittings underneath the sink.\n\nHe also installed a new laundry box to allow for an additional drain pipe for our washer and water softener, as well as replaced our broken exterior dryer vent cover.\n\nI would highly recommend CTA Plumbing 100 for any and all of your plumbing needs."},
  {name:"Bruce Hiller",text:"Caden was extremely thorough and showed great attention to detail. He took the time to explain the service and what the work would entail. Once the job was completed, he explained what he found.\n\nVery honest and fair. I will use CTA Plumbing 100 again."},
  {name:"Chris Hart",text:"Robert, our plumber, was quick to arrive, extremely friendly, and knew exactly how to make the necessary repairs. He quickly fixed our plumbing issue.\n\nI highly recommend CTA Plumbing 100."},
] as const;
function EmergencyButton({className=""}:{className?:string}){return <a href={emergencyHref} className={`inline-flex min-h-14 items-center justify-center gap-2 rounded-xl bg-emergency px-6 font-black text-white shadow-lg transition hover:bg-red-700 focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-white ${className}`}><Phone/>Plumbing Emergency? Call Now</a>}
function Offer({amount,label}:{amount:string;label:string}){return <div className="rounded-2xl border border-copper/40 bg-white/10 p-4 backdrop-blur"><p className="text-xs font-black uppercase tracking-[.18em] text-copper-light">Limited-time offer</p><p className="mt-1 text-3xl font-black text-white">{amount}</p><p className="mt-1 text-sm font-semibold text-slate-200">{label}</p></div>}

export default function EstimateLandingPage(){const schema={"@context":"https://schema.org","@type":"Service",name:"Plumbing estimates and installation services",provider:{"@id":`${site.url}/#business`},areaServed:site.cities.map(city=>({"@type":"City",name:`${city}, Idaho`})),serviceType:["Water softener installation","Water heater installation","Plumbing repair","Drain and sewer service"],url:`${site.url}/estimate-a`};return <div className="estimate-funnel bg-[#fffdf8] text-slate-700">
  <JsonLd data={schema}/><style>{`body:has(.estimate-funnel){padding-bottom:0!important}`}</style>
  <header className="border-b border-white/10 bg-navy text-white"><div className="container flex min-h-20 items-center justify-between gap-4"><Link href="/" aria-label="CTA Plumbing 100 home"><Image src="/images/logo-source.webp" alt="CTA Plumbing 100" width={66} height={66} priority className="size-16 rounded-xl"/></Link><p className="hidden text-sm font-semibold text-slate-300 sm:block">Serving Nampa and the Treasure Valley</p><a href={emergencyHref} className="inline-flex min-h-11 items-center gap-2 rounded-lg bg-emergency px-4 text-sm font-black text-white"><Phone className="size-4"/>208-247-0906</a></div></header>
  <main>
    <section className="relative overflow-hidden bg-navy text-white"><Image src="/images/hero-plumber.webp" alt="CTA Plumbing 100 technician ready to provide a Treasure Valley plumbing estimate" fill priority className="object-cover opacity-25" sizes="100vw"/><div className="absolute inset-0 bg-gradient-to-r from-navy via-navy/95 to-navy/60"/><div className="container relative grid min-h-[720px] items-center gap-10 py-12 lg:grid-cols-[1.08fr_.92fr] lg:py-16"><div><p className="text-sm font-black uppercase tracking-[.2em] text-copper-light">Local Treasure Valley plumbing estimates</p><h1 className="mt-4 max-w-3xl text-4xl font-black leading-[1.02] tracking-tight sm:text-5xl lg:text-6xl">Get a clear estimate from a plumbing team you can trust.</h1><p className="mt-5 max-w-2xl text-lg leading-8 text-slate-200">Tell us what your property needs. CTA Plumbing 100 provides straightforward, professional plumbing service for homes and businesses across the Treasure Valley.</p><div className="mt-7 grid max-w-2xl gap-4 sm:grid-cols-2"><Offer amount="$250 off" label="Water softener installation"/><Offer amount="$200 off" label="Water heater installation"/></div><div className="mt-7 flex flex-col gap-3 sm:flex-row"><a href="#estimate-form" className="inline-flex min-h-14 items-center justify-center gap-2 rounded-xl bg-copper px-7 font-black text-navy shadow-lg hover:bg-copper-light">Get My Free Estimate <ArrowDown className="size-5"/></a><EmergencyButton/></div></div><div id="estimate-form" className="scroll-mt-6"><EstimateForm/></div></div></section>
    <section aria-label="Why customers contact CTA Plumbing" className="border-b border-slate-200 bg-white"><div className="container grid divide-y divide-slate-200 py-2 sm:grid-cols-3 sm:divide-x sm:divide-y-0"><div className="flex items-center justify-center gap-3 px-5 py-5 font-bold text-navy"><MapPin className="text-copper-dark"/>Treasure Valley service area</div><div className="flex items-center justify-center gap-3 px-5 py-5 font-bold text-navy"><ShieldCheck className="text-copper-dark"/>Respect for your property</div><div className="flex items-center justify-center gap-3 px-5 py-5 font-bold text-navy"><Wrench className="text-copper-dark"/>Residential and commercial</div></div></section>
    <section className="py-20"><div className="container grid items-center gap-12 lg:grid-cols-2"><div className="relative min-h-[430px] overflow-hidden rounded-3xl"><Image src="/images/water-system.webp" alt="Water treatment equipment representing a professional water softener installation" fill className="object-cover" sizes="(max-width:1024px) 100vw,50vw"/><div className="absolute left-5 top-5 rounded-xl bg-copper px-5 py-3 font-black text-navy shadow-xl">Limited-time: $250 off</div></div><div><Droplets className="size-11 text-copper-dark"/><p className="mt-5 text-sm font-black uppercase tracking-[.18em] text-copper-dark">Water softener installation</p><h2 className="mt-3 text-4xl font-black tracking-tight text-navy">Make your next water softener installation easier to plan.</h2><p className="mt-5 text-lg leading-8 text-slate-600">Hard water scale can affect fixtures and cleaning. CTA Plumbing 100 can help plan and connect a softening system suited to your property and available space.</p><ul className="mt-6 space-y-3">{["Professional plumbing connections","Equipment placement planned around your property","Straightforward communication about the work"].map(item=><li key={item} className="flex gap-3"><Check className="mt-1 size-5 shrink-0 text-copper-dark"/><span>{item}</span></li>)}</ul><a href="#final-estimate" className="mt-8 inline-flex min-h-12 items-center rounded-xl bg-navy px-6 font-black text-white">Claim $250 Installation Savings</a></div></div></section>
    <section className="bg-slate-50 py-20"><div className="container grid items-center gap-12 lg:grid-cols-2"><div className="relative min-h-[430px] overflow-hidden rounded-3xl lg:order-2"><Image src="/images/water-heater.webp" alt="Water heater equipment for professional installation by CTA Plumbing 100" fill className="object-cover" sizes="(max-width:1024px) 100vw,50vw"/><div className="absolute left-5 top-5 rounded-xl bg-copper px-5 py-3 font-black text-navy shadow-xl">Limited-time: $200 off</div></div><div><Flame className="size-11 text-copper-dark"/><p className="mt-5 text-sm font-black uppercase tracking-[.18em] text-copper-dark">Water heater installation</p><h2 className="mt-3 text-4xl font-black tracking-tight text-navy">Plan dependable hot water with professional installation.</h2><p className="mt-5 text-lg leading-8 text-slate-600">When hot water is unreliable or equipment needs replacement, we help explain practical options for conventional and tankless systems.</p><ul className="mt-6 space-y-3">{["Equipment selected for the property’s needs","Professional installation and plumbing connections","Clear guidance about the installation process"].map(item=><li key={item} className="flex gap-3"><Check className="mt-1 size-5 shrink-0 text-copper-dark"/><span>{item}</span></li>)}</ul><a href="#final-estimate" className="mt-8 inline-flex min-h-12 items-center rounded-xl bg-navy px-6 font-black text-white">Claim $200 Installation Savings</a></div></div></section>
    <section className="py-20"><div className="container max-w-5xl text-center"><p className="text-sm font-black uppercase tracking-[.18em] text-copper-dark">See our work</p><h2 className="mt-3 text-4xl font-black text-navy">A closer look at CTA Plumbing 100</h2><p className="mx-auto mt-4 max-w-2xl leading-7 text-slate-600">Meet the local team ready to help with plumbing projects throughout the Treasure Valley.</p><div className="mt-9 overflow-hidden rounded-3xl bg-navy shadow-xl"><video className="aspect-video w-full bg-navy object-cover" controls preload="metadata" playsInline poster="/videos/cta-plumbing-home-intro-poster.jpg" aria-label="CTA Plumbing 100 introduction video"><source src="/videos/cta-plumbing-home-intro.mp4" type="video/mp4"/>Your browser does not support embedded video. <a href="/videos/cta-plumbing-home-intro.mp4">Download the CTA Plumbing 100 introduction video.</a></video></div></div></section>
    <section className="bg-slate-50 py-20"><div className="container"><div className="mx-auto max-w-3xl text-center"><p className="text-sm font-black uppercase tracking-[.18em] text-copper-dark">Recent projects</p><h2 className="mt-3 text-4xl font-black text-navy">CTA Plumbing 100 at work</h2><p className="mt-4 leading-7 text-slate-600">A look at our team serving homeowners and completing plumbing projects across the Treasure Valley.</p></div><div className="mt-10 grid gap-6 sm:grid-cols-2 lg:grid-cols-3">{[["/images/cta-water-softener-installation.webp","CTA Plumbing technicians moving water softener equipment into a Treasure Valley home","Water softener equipment delivery"],["/images/cta-customer-water-system.webp","CTA Plumbing technician speaking with a homeowner beside installed water treatment equipment","Clear communication with homeowners"],["/images/cta-team-project-delivery.webp","CTA Plumbing team delivering boxed plumbing fixtures at a residential project","Team coordination on a residential project"]].map(([src,alt,caption])=><figure key={src} className="overflow-hidden rounded-2xl bg-white shadow-lg"><div className="relative aspect-[4/3]"><Image src={src} alt={alt} fill className="object-cover" sizes="(max-width:640px) 100vw,33vw"/></div><figcaption className="p-4 text-sm font-bold text-navy">{caption}</figcaption></figure>)}</div></div></section>
    <section className="py-20"><div className="container"><div className="mx-auto max-w-3xl text-center"><p className="text-sm font-black uppercase tracking-[.18em] text-copper-dark">Why choose CTA Plumbing?</p><h2 className="mt-3 text-4xl font-black text-navy">Service built around clear expectations.</h2></div><div className="mt-10 grid gap-6 md:grid-cols-3">{[[ShieldCheck,"Respect for your property","Thoughtful work in occupied homes and business spaces."],[Wrench,"Useful solutions","Recommendations begin with the plumbing problem and the property’s needs."],[Phone,"Clear communication","We explain what we find and help you understand the practical next step."]].map(([Icon,title,text])=>{const C=Icon as typeof Wrench;return <article key={String(title)} className="rounded-2xl border border-slate-200 bg-white p-7 shadow-lg"><C className="size-9 text-copper-dark"/><h3 className="mt-5 text-xl font-black text-navy">{String(title)}</h3><p className="mt-3 leading-7 text-slate-600">{String(text)}</p></article>})}</div></div></section>
    <section className="bg-navy py-20 text-white"><div className="container"><div className="mx-auto max-w-3xl text-center"><p className="text-sm font-black uppercase tracking-[.18em] text-copper-light">Customer reviews</p><h2 className="mt-3 text-4xl font-black">What Treasure Valley customers say</h2></div><div className="mt-10 grid items-start gap-6 lg:grid-cols-3">{reviews.map(review=><article key={review.name} className="rounded-2xl bg-white p-7 text-slate-700 shadow-xl"><div className="flex gap-1 text-copper" aria-label="Five out of five stars">{Array.from({length:5}).map((_,i)=><Star key={i} className="size-5 fill-current" aria-hidden="true"/>)}</div><blockquote className="mt-5 whitespace-pre-line leading-7">“{review.text}”</blockquote><p className="mt-6 border-t border-slate-200 pt-5 font-black text-navy">{review.name}</p></article>)}</div><div className="mt-9 text-center"><a href="https://g.page/r/Cd2Na7Yt-yUEEAE/review" target="_blank" rel="noopener noreferrer" className="inline-flex items-center gap-2 font-bold text-copper-light">Read more reviews <ExternalLink className="size-4"/></a></div></div></section>
    <section className="py-20"><div className="container grid gap-10 lg:grid-cols-[.7fr_1.3fr]"><div><MapPin className="size-11 text-copper-dark"/><p className="mt-5 text-sm font-black uppercase tracking-[.18em] text-copper-dark">Service area</p><h2 className="mt-3 text-4xl font-black text-navy">Serving the Treasure Valley from Nampa.</h2><p className="mt-5 leading-8 text-slate-600">Contact us with your property address to confirm availability in your neighborhood.</p></div><div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-4">{site.cities.map(city=><div key={city} className="rounded-xl border border-slate-200 bg-white p-4 text-center font-black text-navy shadow-sm">{city}, Idaho</div>)}</div></div></section>
    <section id="final-estimate" className="scroll-mt-6 bg-copper py-20"><div className="container grid items-center gap-10 lg:grid-cols-[.9fr_1.1fr]"><div><p className="text-sm font-black uppercase tracking-[.18em] text-navy/70">Limited-time installation offers</p><h2 className="mt-3 text-4xl font-black tracking-tight text-navy sm:text-5xl">Ready for a clear plumbing estimate?</h2><div className="mt-6 grid gap-3 sm:grid-cols-2"><div className="rounded-xl bg-white/60 p-4 font-black text-navy">$250 off water softener installation</div><div className="rounded-xl bg-white/60 p-4 font-black text-navy">$200 off water heater installation</div></div><EmergencyButton className="mt-6 w-full sm:w-auto"/></div><EstimateForm compact/></div></section>
  </main>
  <footer className="bg-navy pb-24 text-slate-300 md:pb-0"><div className="container flex flex-col gap-6 py-10 sm:flex-row sm:items-center sm:justify-between"><div className="flex items-center gap-4"><Image src="/images/logo-source.webp" alt="CTA Plumbing 100" width={64} height={64} className="size-16 rounded-xl"/><div><p className="font-black text-white">CTA Plumbing 100</p><p className="text-sm">{site.email}</p><p className="text-sm">Nampa and the Treasure Valley, Idaho</p></div></div><nav className="flex flex-wrap gap-5 text-sm"><Link href="/privacy-policy">Privacy Policy</Link><Link href="/terms-and-conditions">Terms and Conditions</Link><Link href="/">Main Website</Link></nav></div></footer>
  <div className="fixed inset-x-0 bottom-0 z-50 grid grid-cols-2 border-t border-white/20 bg-navy p-2 shadow-2xl md:hidden"><a href="#estimate-form" className="flex min-h-14 items-center justify-center rounded-l-xl bg-copper px-3 text-center text-sm font-black text-navy">Free Estimate</a><a href={emergencyHref} className="flex min-h-14 items-center justify-center gap-2 rounded-r-xl bg-emergency px-3 text-center text-sm font-black text-white"><Phone className="size-4"/>Emergency Call</a></div>
</div>}
