import type { Metadata } from "next";
import Link from "next/link";
import { ArrowRight } from "lucide-react";
import { Breadcrumbs, FinalCTA } from "@/components/shared";
import { locations, services } from "@/lib/content";

export const metadata: Metadata = { title: "Website Sitemap", description: "Browse every public page on the CTA Plumbing 100 website.", alternates: { canonical: "/sitemap" } };
const mainPages = [["Home","/"],["About Us","/about"],["Services","/services"],["Service Areas","/service-areas"],["Emergency Plumbing","/emergency-plumbing"],["Employment","/employment"],["Contact Us","/contact"],["Privacy Policy","/privacy-policy"],["Terms and Conditions","/terms-and-conditions"]] as const;
function LinkList({ items }: { items: readonly (readonly [string,string])[] }) { return <ul className="grid gap-3 sm:grid-cols-2">{items.map(([label,href])=><li key={href}><Link href={href} className="flex items-center justify-between rounded-xl border border-slate-200 bg-white p-4 font-bold text-navy transition hover:border-copper"><span>{label}</span><ArrowRight className="size-4 text-copper-dark"/></Link></li>)}</ul> }
export default function SitemapPage(){const serviceLinks=services.map((service)=>[service.name,service.slug==="emergency-plumbing"?"/emergency-plumbing":`/services/${service.slug}`] as const);const areaLinks=locations.map((location)=>[`Plumbing in ${location.city}`,`/service-areas/${location.slug}`] as const);return <><div className="page-hero"><Breadcrumbs items={[{label:"Sitemap"}]}/><div className="container relative z-10 max-w-4xl py-16 sm:py-24"><p className="eyebrow !text-copper-light">Website directory</p><h1 className="font-display text-5xl font-black tracking-tight sm:text-6xl">CTA Plumbing 100 Sitemap</h1><p className="mt-6 max-w-2xl text-lg leading-8 text-slate-300">Use this page to find every public section of the CTA Plumbing 100 website.</p></div></div><section className="py-20"><div className="container space-y-14"><div><h2 className="mb-6 text-3xl font-black text-navy">Main pages</h2><LinkList items={mainPages}/></div><div><h2 className="mb-6 text-3xl font-black text-navy">Plumbing services</h2><LinkList items={serviceLinks}/></div><div><h2 className="mb-6 text-3xl font-black text-navy">Service area pages</h2><LinkList items={areaLinks}/></div></div></section><FinalCTA/></>}
