import type { Metadata } from "next";
import { Clock, Mail, MapPin, Phone } from "lucide-react";
import { Breadcrumbs, EmergencyBar } from "@/components/shared";
import { LeadForm } from "@/components/lead-form";
import { JsonLd } from "@/components/json-ld";
import { emailHref, phoneHref, site } from "@/lib/site";
import { fullAddress } from "@/lib/site";
import { LocationMap } from "@/components/location-map";
export const metadata: Metadata = { title: "Contact Us", description: "Request plumbing service from CTA Plumbing 100 in Nampa and across the Treasure Valley.", alternates: { canonical: "/contact" } };
export default function ContactPage() { const schema={"@context":"https://schema.org","@type":"ContactPage",name:"Contact CTA Plumbing 100",url:`${site.url}/contact`,mainEntity:{"@id":`${site.url}/#business`}}; return <><JsonLd data={schema}/><div className="page-hero"><Breadcrumbs items={[{ label: "Contact Us" }]} /><div className="container relative z-10 max-w-4xl py-16 sm:py-24"><p className="eyebrow !text-copper-light">Request plumbing service</p><h1 className="font-display text-5xl font-black tracking-tight sm:text-6xl">Tell us where you need help.</h1><p className="mt-6 max-w-2xl text-lg leading-8 text-slate-300">Send the service address and a useful description, or call our 24/7 emergency line for an urgent plumbing problem.</p></div></div><EmergencyBar /><section className="bg-slate-50 py-20"><div className="container grid gap-10 lg:grid-cols-[.7fr_1.3fr]"><div><h2 className="text-3xl font-black text-navy">Contact details</h2><a className="mt-8 flex gap-4" href={phoneHref}><Phone className="text-copper-dark"/><span><strong className="block text-navy">Phone</strong>{site.phone}</span></a><a className="mt-6 flex gap-4" href={emailHref}><Mail className="text-copper-dark"/><span><strong className="block text-navy">Email</strong>{site.email}</span></a><p className="mt-6 flex gap-4"><Clock className="text-copper-dark"/><span><strong className="block text-navy">Business hours</strong>{site.hours}<br /><strong className="text-emergency">{site.emergencyHours}</strong></span></p><p className="mt-6 flex gap-4"><MapPin className="text-copper-dark"/><span><strong className="block text-navy">Business address</strong>{fullAddress}<br />Serving {site.area}</span></p></div><LeadForm /></div></section><section className="py-20"><div className="container"><div className="mb-8"><p className="eyebrow">Find us in Nampa</p><h2 className="section-title">Location and directions</h2><p className="section-copy">Use the map for directions to CTA Plumbing 100. For service at your property, submit the address in the request form or call us.</p></div><LocationMap compact /></div></section></> }
