import Image from "next/image";
import Link from "next/link";
import { ArrowRight, Building2, CalendarCheck, ExternalLink, Facebook, Home, Instagram, MessageSquareText, ShieldCheck, Star, Wrench } from "lucide-react";
import { Button } from "@/components/ui/button";
import { CallNow, EmergencyBar, FinalCTA, LocationGrid, SectionHeading, ServiceGrid, SplitImage } from "@/components/shared";
import { FAQList } from "@/components/faq";
import { LeadForm } from "@/components/lead-form";
import { JsonLd } from "@/components/json-ld";
import { site } from "@/lib/site";
import { LocationMap } from "@/components/location-map";

const faqs = [
  { question: "What areas does CTA Plumbing 100 serve?", answer: "CTA Plumbing 100 provides plumbing services in Nampa, Boise, Meridian, Caldwell, Eagle, Kuna, Star, Middleton, and surrounding Treasure Valley communities. Contact us with your service address to confirm availability in your neighborhood." },
  { question: "What residential plumbing services do you provide in Nampa?", answer: "Our Nampa plumbing services include leak and pipe repair, drain cleaning, water heater service, toilets, faucets and fixtures, kitchen and bathroom plumbing, repiping, water filtration, water softeners, sewer line work, and general plumbing repairs." },
  { question: "Do you provide commercial plumbing services in Boise and the Treasure Valley?", answer: "Yes. CTA Plumbing 100 works with businesses, property managers, contractors, and commercial facilities in Boise and across the Treasure Valley. Services include repairs, fixtures, drains, piping, water heaters, tenant improvements, and plumbing remodels." },
  { question: "Does CTA Plumbing 100 provide 24/7 emergency plumbing?", answer: "Yes. Call (208) 795-3366 anytime for burst pipes, major leaks, sewer backups, overflowing toilets, water heater failures, backed up drains, or flooding caused by plumbing throughout the Treasure Valley." },
  { question: "Can you help with water heater repair or replacement in Meridian?", answer: "CTA Plumbing 100 provides water heater troubleshooting, repair, replacement, and installation in Meridian and nearby Treasure Valley communities. We can evaluate unreliable hot water, leaks, unusual noise, and other common water heater concerns." },
  { question: "Do you provide drain cleaning in Caldwell?", answer: "Yes. We provide drain and sewer cleaning in Caldwell and throughout the Treasure Valley. Contact us for slow drains, recurring clogs, gurgling fixtures, sewer odors, or water backing up through a drain." },
  { question: "How do I request a plumbing estimate or schedule service?", answer: "Call (208) 795-3366 or complete the online service request form. Include the property address, city, service needed, and a short description. We will follow up to clarify the work and discuss scheduling or the appropriate estimate process." },
  { question: "Does CTA Plumbing 100 work on both homes and commercial properties?", answer: "Yes. We serve homeowners, property managers, contractors, and commercial customers with plumbing repairs, replacements, improvements, and coordinated project work throughout the Treasure Valley." },
];

const reviews = [
  { name: "Brittany Caylor", text: "Caden was great! He removed an old kitchen sink and faucet and replaced them with new ones, and it looks beautiful. He took his time to do it right and even went to the store to ensure he had the exact materials needed for proper and secure fittings underneath the sink.\n\nHe also installed a new laundry box to allow for an additional drain pipe for our washer and water softener, as well as replaced our broken exterior dryer vent cover.\n\nI would highly recommend CTA Plumbing 100 for any and all of your plumbing needs." },
  { name: "Bruce Hiller", text: "Caden was extremely thorough and showed great attention to detail. He took the time to explain the service and what the work would entail. Once the job was completed, he explained what he found.\n\nVery honest and fair. I will use CTA Plumbing 100 again." },
  { name: "Chris Hart", text: "Robert, our plumber, was quick to arrive, extremely friendly, and knew exactly how to make the necessary repairs. He quickly fixed our plumbing issue.\n\nI highly recommend CTA Plumbing 100." },
] as const;

export default function HomePage() { const faqSchema = { "@context": "https://schema.org", "@type": "FAQPage", mainEntity: faqs.map((faq) => ({ "@type": "Question", name: faq.question, acceptedAnswer: { "@type": "Answer", text: faq.answer } })), url: site.url }; return <>
  <JsonLd data={faqSchema} />
  <section className="relative min-h-[690px] overflow-hidden bg-navy"><Image src="/images/hero-plumber.webp" alt="CTA Plumbing 100 technician carrying professional equipment at a Treasure Valley home" fill priority className="object-cover object-center opacity-45" sizes="100vw" /><div className="absolute inset-0 bg-gradient-to-r from-navy via-navy/90 to-navy/20" /><div className="container relative flex min-h-[690px] items-center py-20"><div className="max-w-3xl text-white"><p className="mb-5 font-black uppercase tracking-[.2em] text-copper-light">Based in Nampa • Treasure Valley service</p><h1 className="font-display text-5xl font-black leading-[.98] tracking-tight sm:text-6xl lg:text-7xl">Professional plumbing across the Treasure Valley.</h1><p className="mt-6 max-w-2xl text-lg leading-8 text-slate-200">Dependable residential and commercial plumbing for Nampa, Boise, Meridian, and surrounding communities, backed by honest communication and respect for your property.</p><div className="mt-8 flex flex-wrap gap-3"><CallNow /><Button variant="outline" size="lg" asChild><Link href="/contact">Request Service <ArrowRight /></Link></Button><Button variant="emergency" size="lg" asChild><Link href="/emergency-plumbing">Emergency Help</Link></Button></div><div className="mt-9 grid max-w-2xl gap-3 text-sm font-semibold sm:grid-cols-3"><span>✓ Residential &amp; commercial</span><span>✓ Clear communication</span><span>✓ Local service focus</span></div></div></div></section>
  <EmergencyBar />
  <section className="py-20"><div className="container"><SectionHeading eyebrow="Plumbing services" title="One local team for the plumbing work your property needs." text="From everyday fixture repairs to water heaters, drains, piping, and commercial projects, we help you understand the next step." /><ServiceGrid limit={6} /><div className="mt-8 text-center"><Button variant="navy" asChild><Link href="/services">View all services <ArrowRight /></Link></Button></div></div></section>
  <section className="bg-slate-50 py-20"><SplitImage src="/images/customer-consultation.webp" alt="CTA Plumbing 100 technician explaining plumbing work to a customer"><SectionHeading eyebrow="Why CTA Plumbing 100" title="Service built around clear expectations." /><div className="grid gap-5 sm:grid-cols-2">{[[MessageSquareText,"Honest communication","We explain what we find and the practical options available."],[CalendarCheck,"Reliable scheduling","We communicate about timing and make it easier to plan around the visit."],[ShieldCheck,"Respect for your property","We work thoughtfully in occupied homes and business spaces."],[Wrench,"Useful solutions","Recommendations start with the problem and avoid unsupported sales claims."]].map(([Icon,title,text]) => { const C=Icon as typeof Wrench; return <div key={String(title)}><C className="text-copper-dark" /><h3 className="mt-3 font-black text-navy">{String(title)}</h3><p className="mt-1 leading-7 text-slate-600">{String(text)}</p></div>})}</div></SplitImage></section>
  <section className="py-20"><div className="container grid gap-6 lg:grid-cols-2"><article className="rounded-3xl bg-navy p-8 text-white sm:p-10"><Home className="size-10 text-copper" /><h2 className="mt-6 text-3xl font-black">Residential plumbing</h2><p className="mt-4 leading-8 text-slate-300">Helpful service for the leaks, drains, fixtures, water systems, piping, and improvements that keep a home functioning.</p><Button className="mt-6" asChild><Link href="/contact">Request home service</Link></Button></article><article className="rounded-3xl border border-slate-200 p-8 sm:p-10"><Building2 className="size-10 text-copper-dark" /><h2 className="mt-6 text-3xl font-black text-navy">Commercial plumbing</h2><p className="mt-4 leading-8 text-slate-600">Responsive plumbing support for property managers, contractors, facilities, tenant improvements, and commercial spaces.</p><Button className="mt-6" variant="navy" asChild><Link href="/services/commercial-plumbing">Explore commercial service</Link></Button></article></div></section>
  <section className="bg-slate-50 py-20"><div className="container"><SectionHeading eyebrow="Service area" title="Local plumbing support across the Treasure Valley." text="Nampa is central to our service area, with plumbing service available throughout the valley’s primary communities." /><LocationGrid /></div></section>
  <section className="py-20"><div className="container"><SectionHeading eyebrow="Nampa location" title="CTA Plumbing 100 in the heart of the Treasure Valley." text="Our Nampa location provides a central starting point for serving customers throughout the valley. Open the map for directions or contact us to confirm service availability at your property." /><LocationMap /></div></section>
  <section className="py-20"><div className="container"><SectionHeading center eyebrow="Customer reviews" title="Trusted by Treasure Valley customers." text="Read what customers have shared about their experience with CTA Plumbing 100." /><div className="grid items-start gap-6 lg:grid-cols-3">{reviews.map((review)=><article className="card relative overflow-hidden" key={review.name}><div className="absolute inset-x-0 top-0 h-1 bg-copper"/><div className="flex gap-1 text-copper" aria-label="Five out of five stars">{Array.from({length:5}).map((_,index)=><Star key={index} className="size-5 fill-current" aria-hidden="true"/>)}</div><blockquote className="mt-5 whitespace-pre-line leading-7 text-slate-600">“{review.text}”</blockquote><p className="mt-6 border-t border-slate-200 pt-5 font-black text-navy">{review.name}</p></article>)}</div><div className="mt-10 text-center"><Button variant="navy" size="lg" asChild><a href="https://g.page/r/Cd2Na7Yt-yUEEAE/review" target="_blank" rel="noopener noreferrer">Read More Reviews <ExternalLink className="size-4"/></a></Button></div></div></section>
  <section className="overflow-hidden bg-slate-50 py-20"><div className="container"><div className="relative overflow-hidden rounded-3xl bg-navy px-6 py-12 text-center shadow-xl sm:px-12 sm:py-16"><div className="absolute -left-20 -top-20 size-64 rounded-full bg-copper/10"/><div className="absolute -bottom-24 -right-16 size-72 rounded-full bg-white/5"/><div className="relative mx-auto max-w-3xl"><p className="eyebrow !text-copper-light">Connect with CTA Plumbing 100</p><h2 className="section-title !text-white">We’re Social</h2><p className="mx-auto mt-4 max-w-2xl text-lg leading-8 text-slate-300">Follow along to see our latest projects, transformations, and behind the scenes work throughout the Treasure Valley.</p><div className="mt-9 flex flex-col justify-center gap-4 sm:flex-row"><a href="https://www.instagram.com/cta_plumbingidaho/" target="_blank" rel="noopener noreferrer" className="inline-flex min-h-14 items-center justify-center gap-3 rounded-xl bg-gradient-to-r from-fuchsia-600 via-rose-500 to-amber-500 px-7 font-black text-white shadow-lg transition hover:-translate-y-0.5 hover:shadow-xl focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-white focus-visible:ring-offset-2 focus-visible:ring-offset-navy"><Instagram aria-hidden="true"/>Follow Us on Instagram <ExternalLink className="size-4" aria-hidden="true"/></a><a href="https://www.facebook.com/CTAPLUMBING100/" target="_blank" rel="noopener noreferrer" className="inline-flex min-h-14 items-center justify-center gap-3 rounded-xl bg-[#1877F2] px-7 font-black text-white shadow-lg transition hover:-translate-y-0.5 hover:bg-[#1265d5] hover:shadow-xl focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-white focus-visible:ring-offset-2 focus-visible:ring-offset-navy"><Facebook aria-hidden="true"/>Follow Us on Facebook <ExternalLink className="size-4" aria-hidden="true"/></a></div></div></div></div></section>
  <section className="bg-navy py-20"><div className="container grid gap-10 lg:grid-cols-[.8fr_1.2fr]"><div><p className="eyebrow !text-copper-light">Request service</p><h2 className="section-title !text-white">Tell us what’s happening.</h2><p className="section-copy !text-slate-300">Share the service address and a few useful details. For urgent property risk, call our 24/7 emergency plumbing line.</p></div><LeadForm /></div></section>
  <section className="py-20"><div className="container max-w-4xl"><SectionHeading center eyebrow="Frequently asked questions" title="Straight answers before you schedule." /><FAQList items={faqs} /></div></section>
  <FinalCTA />
  </> }
