import type { Metadata } from "next";
import Link from "next/link";
import { Breadcrumbs } from "@/components/shared";
import { site } from "@/lib/site";

export const metadata: Metadata = { title: "Privacy Policy", description: "Read the CTA Plumbing 100 website Privacy Policy.", alternates: { canonical: "/privacy-policy" } };

export default function PrivacyPage() {
  return <>
    <div className="page-hero"><Breadcrumbs items={[{ label: "Privacy Policy" }]} /><div className="container relative z-10 max-w-4xl py-16 sm:py-24"><p className="eyebrow !text-copper-light">Website information</p><h1 className="font-display text-5xl font-black tracking-tight sm:text-6xl">Privacy Policy</h1><p className="mt-5 text-slate-300">Effective date: August 27, 2026</p></div></div>
    <article className="container max-w-4xl space-y-10 py-20 leading-8 text-slate-600">
      <section><h2 className="text-2xl font-black text-navy">Overview</h2><p className="mt-3">CTA Plumbing 100 respects your privacy. This policy explains what personal information we collect, how we use and protect it, and the choices available to you.</p></section>
      <section><h2 className="text-2xl font-black text-navy">Information we collect</h2><p className="mt-3">We may collect your name, phone number, email address, service address, city, property information, requested service, urgency, preferred contact method, messages, form responses, and SMS opt-in consent choice. Employment applications may also include a position of interest, resume, employment history, education, qualifications, and other information contained in an uploaded document.</p><p className="mt-3">We may automatically receive technical information such as device and browser type, IP address, referring page, pages visited, approximate location, and advertising or analytics identifiers.</p></section>
      <section><h2 className="text-2xl font-black text-navy">How information is used</h2><p className="mt-3">Information may be used to respond to inquiries, evaluate service requests, schedule and provide services, prepare estimates, send requested communications, provide customer support, review employment applications, measure advertising and website performance, maintain security, improve the website, and comply with legal obligations.</p></section>
      <section><h2 className="text-2xl font-black text-navy">SMS consent and opt-in information</h2><p className="mt-3">When you voluntarily check an SMS consent box, CTA Plumbing 100 may send recurring informational and promotional text messages consistent with the disclosure shown at the time of consent. Consent is optional and is not a condition of purchase. Message frequency varies. Message and data rates may apply. Reply STOP to unsubscribe or HELP for assistance.</p><p className="mt-3 font-semibold text-navy">Mobile information, including phone numbers and SMS opt-in consent data, will not be sold, rented, or shared with third parties or affiliates for marketing or promotional purposes. SMS opt-in consent data will not be shared with any third parties.</p></section>
      <section><h2 className="text-2xl font-black text-navy">Cookies and tracking technologies</h2><p className="mt-3">The website may use cookies, session technologies, analytics, call tracking, advertising measurement, and similar technologies for essential functionality, security, performance measurement, attribution, and website improvement. These technologies may collect browser, device, page-view, referral, and advertising identifier information. You can manage cookies through your browser settings, although disabling them may affect website functionality.</p></section>
      <section><h2 className="text-2xl font-black text-navy">Third-party services</h2><p className="mt-3">The website may use service providers for hosting, email delivery, maps, analytics, advertising measurement, spam prevention, and other business operations. These providers may process information only as needed to provide their services and according to applicable agreements and privacy obligations.</p></section>
      <section><h2 className="text-2xl font-black text-navy">Resume uploads and retention</h2><p className="mt-3">Resumes are collected for employment-related purposes and are sent to the designated CTA Plumbing 100 application recipient. Applications may be retained for consideration for current or future opportunities and as required by applicable law.</p></section>
      <section><h2 className="text-2xl font-black text-navy">Data security</h2><p className="mt-3">CTA Plumbing 100 uses reasonable administrative, technical, and organizational safeguards designed to protect submitted information from unauthorized access, alteration, loss, or misuse. No internet transmission or storage method can be guaranteed completely secure, so please do not submit sensitive information that a form does not request.</p></section>
      <section><h2 className="text-2xl font-black text-navy">Your rights and choices</h2><p className="mt-3">You may contact CTA Plumbing 100 to ask about personal information you submitted or to request access, correction, updating, or deletion when applicable. To stop text messages, reply STOP. To request assistance, reply HELP. You may also contact us using the information below to update your communication preferences. Legal rights may vary by location and are subject to applicable law.</p></section>
      <section><h2 className="text-2xl font-black text-navy">Policy updates</h2><p className="mt-3">This policy may be revised as website practices, services, or legal requirements change. The effective date at the top of this page will be updated when material revisions are published.</p></section>
      <section><h2 className="text-2xl font-black text-navy">Contact us</h2><p className="mt-3">Questions about this Privacy Policy may be sent to <a className="font-bold text-copper-dark" href={`mailto:${site.email}`}>{site.email}</a>, by phone at <a className="font-bold text-copper-dark" href={`tel:${site.phone.replace(/[^+\d]/g, "")}`}>{site.phone}</a>, or through the <Link className="font-bold text-copper-dark" href="/contact">Contact Us page</Link>.</p></section>
    </article>
  </>;
}
