"use client";

import Image from "next/image";
import Link from "next/link";
import { ArrowDown, Check, Clock3, MapPin, Phone, ShieldCheck, Sparkles, Star } from "lucide-react";
import type { Campaign } from "@/lib/campaigns";
import { campaignPhoneDisplay, campaignPhoneHref } from "@/lib/campaigns";
import { CampaignForm } from "@/components/campaign-form";
import { trackCampaignEvent } from "@/components/campaign-tracking";

const reviews=[
  {name:"Bruce Hiller",text:"Caden was extremely thorough and showed great attention to detail. He took the time to explain the service and what the work would entail. Once the job was completed, he explained what he found. Very honest and fair. I will use CTA Plumbing 100 again."},
  {name:"Chris Hart",text:"Robert, our plumber, was quick to arrive, extremely friendly, and knew exactly how to make the necessary repairs. He quickly fixed our plumbing issue. I highly recommend CTA Plumbing 100."},
];

function CallLink({campaign,label,className=""}:{campaign:Campaign;label:string;className?:string}){return <a onClick={()=>trackCampaignEvent("campaign_call_click",campaign.id,{placement:label})} href={campaignPhoneHref(campaign.phone)} className={className}><Phone className="size-5 shrink-0"/>{label}</a>}
function AppointmentLink({campaign,label,className=""}:{campaign:Campaign;label:string;className?:string}){return <a onClick={()=>trackCampaignEvent("campaign_appointment_click",campaign.id,{placement:label})} href="#appointment-form" className={className}>{label}<ArrowDown className="size-5"/></a>}

function SpeedOfferBadge(){return <div className="speed-offer-badge mt-5 flex max-w-xl items-center gap-4 overflow-hidden rounded-2xl border border-copper-light/50 bg-white/10 p-4 shadow-2xl backdrop-blur-sm" aria-label="60-minute qualifying arrival offer">
  <div className="speed-clock relative grid size-20 shrink-0 place-items-center rounded-full border-4 border-copper bg-navy shadow-[0_0_28px_rgba(184,154,85,.45)]" aria-hidden="true"><span className="absolute inset-[7px] rounded-full border border-copper-light/40"/><span className="speed-clock-hand speed-clock-minute"/><span className="speed-clock-hand speed-clock-hour"/><span className="relative z-10 size-2 rounded-full bg-emergency"/></div>
  <div><div className="flex items-center gap-2 text-copper-light"><Sparkles className="size-4"/><p className="text-xs font-black uppercase tracking-[.18em]">Fast response offer</p></div><p className="mt-1 text-2xl font-black leading-tight text-white">60 minutes or <span className="text-copper-light">$100 off</span></p><p className="mt-1 text-xs leading-5 text-slate-300">For phone-confirmed qualifying calls.</p></div>
  </div>}

export function CampaignLandingPage({campaign}:{campaign:Campaign}){
  const call=`Call ${campaignPhoneDisplay(campaign.phone)}`;
  return <div className="min-h-screen bg-[#fffdf8] pb-20 text-slate-700 md:pb-0">
    <header className="border-b border-white/10 bg-navy text-white"><div className="container flex min-h-20 items-center justify-between gap-4 py-3"><Image src="/images/logo-source.webp" alt="CTA Plumbing 100" width={64} height={64} priority className="size-16 rounded-lg"/><CallLink campaign={campaign} label={call} className="inline-flex min-h-12 items-center gap-2 rounded-xl bg-emergency px-4 text-sm font-black text-white shadow-lg sm:px-6 sm:text-base"/></div></header>
    <main>
      <section className="relative overflow-hidden bg-navy text-white"><Image src={campaign.image} alt={campaign.imageAlt} fill priority className="object-cover opacity-25" sizes="100vw"/><div className="absolute inset-0 bg-gradient-to-r from-navy via-navy/95 to-navy/55"/><div className="container relative grid items-center gap-8 py-10 lg:min-h-[680px] lg:grid-cols-[1.08fr_.92fr] lg:py-16">
        <div><p className="text-sm font-black uppercase tracking-[.18em] text-copper-light">{campaign.eyebrow}</p>{campaign.slug==="60-minute-plumber"?<SpeedOfferBadge/>:<div className="mt-4 inline-flex rounded-xl border border-copper-light/40 bg-copper px-5 py-3 text-xl font-black text-navy shadow-xl">{campaign.offerLabel}</div>}<h1 className="mt-5 max-w-3xl text-4xl font-black leading-[1.02] tracking-tight sm:text-5xl lg:text-6xl">{campaign.headline}</h1><p className="mt-5 max-w-2xl text-lg leading-8 text-slate-200">{campaign.supportingCopy}</p>{campaign.qualifier&&<p className="mt-4 max-w-2xl rounded-xl border border-copper-light/40 bg-white/10 p-4 text-sm font-bold leading-6 text-white">{campaign.qualifier}</p>}
          <div className="mt-6 flex flex-col gap-3 sm:flex-row"><CallLink campaign={campaign} label={call} className="inline-flex min-h-14 items-center justify-center gap-2 rounded-xl bg-emergency px-6 font-black text-white shadow-lg"/><AppointmentLink campaign={campaign} label="Request an Appointment" className="inline-flex min-h-14 items-center justify-center gap-2 rounded-xl border-2 border-white bg-white/5 px-6 font-black text-white"/></div>
          <div className="mt-6 flex flex-wrap gap-x-6 gap-y-3 text-sm font-bold text-slate-200"><span className="flex items-center gap-2"><MapPin className="size-4 text-copper-light"/>Local Treasure Valley company</span><span className="flex items-center gap-2"><ShieldCheck className="size-4 text-copper-light"/>Respectful property care</span><span className="flex items-center gap-2"><Clock3 className="size-4 text-copper-light"/>24/7 emergency line</span></div>
        </div><CampaignForm campaign={campaign} instance="primary"/>
      </div></section>

      <section className="bg-copper py-10 text-navy"><div className="container text-center"><h2 className="text-3xl font-black">{campaign.decisionQuestion}</h2><div className="mx-auto mt-6 grid max-w-4xl gap-4 sm:grid-cols-2"><CallLink campaign={campaign} label={campaign.todayLabel} className="inline-flex min-h-16 items-center justify-center gap-2 rounded-xl bg-emergency px-5 font-black text-white shadow-lg"/><AppointmentLink campaign={campaign} label={campaign.laterLabel} className="inline-flex min-h-16 items-center justify-center gap-2 rounded-xl bg-navy px-5 font-black text-white shadow-lg"/></div>{campaign.qualifier&&<p className="mx-auto mt-4 max-w-3xl text-sm font-bold">{campaign.qualifier}</p>}</div></section>

      <section className="py-16 sm:py-20"><div className="container grid items-center gap-10 lg:grid-cols-2"><div><p className="text-sm font-black uppercase tracking-[.18em] text-copper-dark">Clear offer details</p><h2 className="mt-3 text-4xl font-black tracking-tight text-navy">What this offer includes</h2><p className="mt-5 text-lg leading-8 text-slate-600">{campaign.explanation}</p><ul className="mt-6 space-y-3">{campaign.terms.map(term=><li key={term} className="flex gap-3 rounded-xl bg-slate-50 p-4 leading-7"><Check className="mt-1 size-5 shrink-0 text-copper-dark"/><span>{term}</span></li>)}</ul></div><div className="relative aspect-[4/3] overflow-hidden rounded-3xl shadow-xl"><Image src={campaign.image} alt={campaign.imageAlt} fill className="object-cover" sizes="(max-width:1024px) 100vw,50vw"/></div></div></section>

      <section className="bg-slate-50 py-16 sm:py-20"><div className="container"><div className="mx-auto max-w-3xl text-center"><p className="text-sm font-black uppercase tracking-[.18em] text-copper-dark">Why CTA Plumbing 100</p><h2 className="mt-3 text-4xl font-black text-navy">Local plumbing help with clear expectations</h2></div><div className="mt-10 grid gap-5 sm:grid-cols-2 lg:grid-cols-4">{[["Local service","Based in Nampa and serving Treasure Valley communities."],["Straightforward communication","We explain the issue and discuss additional work before moving forward."],["Professional technicians","A plumbing team prepared to diagnose and address the work requested."],["Respect for your home","Thoughtful service in occupied homes and business spaces."]].map(([title,text])=><article key={title} className="rounded-2xl bg-white p-6 shadow-lg"><Check className="size-8 text-copper-dark"/><h3 className="mt-4 text-xl font-black text-navy">{title}</h3><p className="mt-3 leading-7 text-slate-600">{text}</p></article>)}</div></div></section>

      <section className="py-16 sm:py-20"><div className="container"><div className="mx-auto max-w-3xl text-center"><p className="text-sm font-black uppercase tracking-[.18em] text-copper-dark">Customer reviews</p><h2 className="mt-3 text-4xl font-black text-navy">What customers have shared</h2></div><div className="mx-auto mt-10 grid max-w-5xl gap-6 md:grid-cols-2">{reviews.map(review=><article key={review.name} className="rounded-2xl border border-slate-200 bg-white p-6 shadow-lg"><div className="flex gap-1 text-copper" aria-label="Five out of five stars">{Array.from({length:5}).map((_,i)=><Star key={i} className="size-5 fill-current" aria-hidden="true"/>)}</div><blockquote className="mt-5 leading-7 text-slate-600">“{review.text}”</blockquote><p className="mt-5 font-black text-navy">{review.name}</p></article>)}</div></div></section>

      <section className="bg-navy py-16 text-white"><div className="container text-center"><p className="text-sm font-black uppercase tracking-[.18em] text-copper-light">{campaign.offerLabel}</p><h2 className="mx-auto mt-3 max-w-3xl text-4xl font-black">Ready to request plumbing service?</h2><p className="mx-auto mt-4 max-w-2xl leading-7 text-slate-300">Call for service today or send an appointment request and our team will follow up.</p><div className="mx-auto mt-7 flex max-w-2xl flex-col justify-center gap-3 sm:flex-row"><CallLink campaign={campaign} label={call} className="inline-flex min-h-14 items-center justify-center gap-2 rounded-xl bg-emergency px-6 font-black text-white"/><AppointmentLink campaign={campaign} label="Request an Appointment" className="inline-flex min-h-14 items-center justify-center gap-2 rounded-xl bg-copper px-6 font-black text-navy"/></div></div></section>
    </main>
    <footer className="bg-[#080807] py-8 text-slate-300"><div className="container flex flex-col items-center justify-between gap-4 text-center text-sm sm:flex-row sm:text-left"><div><p className="font-bold text-white">CTA Plumbing 100</p><p className="mt-1">8565 E Cash Ln, Nampa, ID 83687</p></div><nav className="flex gap-5" aria-label="Legal links"><Link href="/privacy-policy">Privacy Policy</Link><Link href="/terms-and-conditions">Terms</Link></nav></div></footer>
    <div className="fixed inset-x-0 bottom-0 z-50 grid grid-cols-2 gap-2 border-t border-slate-200 bg-white p-2 shadow-2xl md:hidden"><CallLink campaign={campaign} label="Call Now" className="inline-flex min-h-12 items-center justify-center gap-2 rounded-xl bg-emergency px-3 text-sm font-black text-white"/><AppointmentLink campaign={campaign} label="Request Appointment" className="inline-flex min-h-12 items-center justify-center gap-1 rounded-xl bg-navy px-2 text-xs font-black text-white"/></div>
  </div>
}
