"use client";

import { FormEvent, useEffect, useId, useRef, useState } from "react";
import { ArrowLeft, ArrowRight, Building2, Check, Home, LoaderCircle, Phone } from "lucide-react";
import type { Campaign, CampaignSlug } from "@/lib/campaigns";
import { campaignPhoneDisplay, campaignPhoneHref } from "@/lib/campaigns";
import { trackCampaignEvent } from "@/components/campaign-tracking";
import { SmsConsentFields } from "@/components/sms-consent-fields";

type Answers = { firstName:string;lastName:string;phone:string;email:string;propertyType:string;city:string;state:string;zipCode:string;serviceIssue:string;serviceCondition:string;issueDetail:string;contactTime:string;contactPreference:string;notes:string;smsTransactionalConsent:boolean;smsMarketingConsent:boolean };
type Choice={value:string;label:string};
const initial:Answers={firstName:"",lastName:"",phone:"",email:"",propertyType:"",city:"",state:"Idaho",zipCode:"",serviceIssue:"",serviceCondition:"",issueDetail:"",contactTime:"",contactPreference:"",notes:"",smsTransactionalConsent:false,smsMarketingConsent:false};
const offerContent:Record<CampaignSlug,{stepOne:string;serviceHeading:string;issues:Choice[];conditionHeading?:string;conditions?:Choice[];urgent?:boolean;placeholder:string;submit:string;tag:string}>={
  "99-drain-cleaning":{stepOne:"Claim Your $99 Drain Cleaning",serviceHeading:"What type of drain issue are you experiencing?",issues:["Clogged Kitchen Sink","Clogged Bathroom Sink","Clogged Toilet","Clogged Shower or Tub","Main Sewer Line Concern","Multiple Slow or Clogged Drains","Not Sure"].map(label=>({value:label,label})),conditionHeading:"Is the drain completely blocked or still draining slowly?",conditions:["Completely Blocked","Draining Slowly","Not Sure"].map(label=>({value:label,label})),placeholder:"Tell us which drain is affected or how long it has been clogged.",submit:"Claim My $99 Drain Cleaning",tag:"CTA – $99 Drain Cleaning"},
  "200-water-heater-buyback":{stepOne:"Claim Your $200 Water Buyback",serviceHeading:"What type of water system are you interested in?",issues:["Water Softener","Whole-Home Water Filtration","Reverse Osmosis Drinking Water","Replacing an Existing System","Not Sure—Help Me Choose"].map(label=>({value:label,label})),conditionHeading:"Do you currently have a water treatment or softener system?",conditions:["Yes","No","Not Sure"].map(label=>({value:label,label})),placeholder:"Tell us about your current system or any water-quality concerns.",submit:"Claim My $200 Water Buyback",tag:"CTA – $200 Water Buyback"},
  "200-off-plumbing-repair":{stepOne:"Save $200 on Your Plumbing Repair",serviceHeading:"What plumbing issue can we help with?",issues:["Leaking Pipe","Faucet or Fixture Repair","Toilet Repair","Garbage Disposal","Water Pressure Problem","Water Heater Issue","Sewer or Drain Issue","Other Plumbing Repair","Not Sure"].map(label=>({value:label,label})),placeholder:"Tell us more about the repair you need.",submit:"Claim My $200 Repair Savings",tag:"CTA – $200 Plumbing Repair"},
  "60-minute-plumber":{stepOne:"Request a 60-Minute Plumber",serviceHeading:"What can our plumber help you with?",issues:["Active Leak","Clogged Drain","Toilet Problem","Water Heater Problem","Faucet or Fixture Repair","No Hot Water","Water Pressure Problem","Other Plumbing Issue","Not Sure"].map(label=>({value:label,label})),conditionHeading:"Is this an urgent plumbing issue?",conditions:["Yes—I Need Help as Soon as Possible","Today, If Available","Within the Next Few Days","I’m Flexible"].map(label=>({value:label,label})),urgent:true,placeholder:"Tell us what’s happening and how urgently you need assistance.",submit:"Request My 60-Minute Plumber",tag:"CTA – 60-Minute Plumber"},
};

function ChoiceCards({name,choices,value,onChange,columns=true}:{name:string;choices:Choice[];value:string;onChange:(value:string)=>void;columns?:boolean}){return <div className={`grid gap-2 ${columns?"sm:grid-cols-2":""}`} role="radiogroup" aria-label={name}>{choices.map(choice=><button key={choice.value} type="button" role="radio" aria-checked={value===choice.value} onClick={()=>onChange(choice.value)} className={`group flex min-h-14 items-center justify-between rounded-xl border-2 px-4 py-3 text-left text-sm font-bold transition ${value===choice.value?"border-copper bg-[#f6efdd] text-navy shadow-md":"border-slate-200 bg-white text-slate-700 hover:border-copper/60"}`}><span>{choice.label}</span><span className={`grid size-6 shrink-0 place-items-center rounded-full ${value===choice.value?"bg-copper text-navy":"border border-slate-300"}`}>{value===choice.value&&<Check className="size-4"/>}</span></button>)}</div>}

export function CampaignForm({campaign,instance}:{campaign:Campaign;instance:string}){
  const id=useId();const started=useRef(false);const [step,setStep]=useState(1);const [answers,setAnswers]=useState<Answers>(initial);const [error,setError]=useState("");const [busy,setBusy]=useState(false);const content=offerContent[campaign.slug];
  const field="mt-2 min-h-12 w-full rounded-xl border border-slate-300 bg-white px-4 text-navy outline-none transition focus:border-copper focus:ring-2 focus:ring-copper/30";
  useEffect(()=>{if(instance==="primary")trackCampaignEvent("campaign_page_view",campaign.id,{page_path:location.pathname})},[campaign.id,instance]);
  function update<K extends keyof Answers>(key:K,value:Answers[K]){setAnswers(current=>({...current,[key]:value}));setError("")}
  function start(){if(!started.current){started.current=true;trackCampaignEvent("campaign_form_start",campaign.id,{form_instance:instance})}}
  function valid(current:number){if(current===1){if(!answers.firstName.trim()||!answers.lastName.trim())return"Please enter your first and last name.";if(!/^[-+()\d\s.]{7,30}$/.test(answers.phone))return"Please enter a valid phone number.";if(answers.email&&!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(answers.email))return"Please enter a valid email address or leave it blank."}if(current===2){if(!answers.propertyType)return"Please choose residential or commercial.";if(!answers.city.trim()||!/^\d{5}(?:-\d{4})?$/.test(answers.zipCode))return"Please enter the property city and a valid ZIP code."}if(current===3){if(!answers.serviceIssue)return"Please choose the option that best describes the service needed.";if(content.conditions&&!answers.serviceCondition)return"Please answer the follow-up service question."}return""}
  function next(){const message=valid(step);if(message){setError(message);return}setStep(value=>Math.min(4,value+1));trackCampaignEvent("campaign_form_step",campaign.id,{step_completed:step,form_instance:instance})}
  function back(){setError("");setStep(value=>Math.max(1,value-1))}
  async function submit(event:FormEvent<HTMLFormElement>){event.preventDefault();if(busy)return;if(!answers.contactTime||!answers.contactPreference){setError("Please select the best contact time and contact method.");return}setBusy(true);setError("");const params=new URLSearchParams(location.search);const payload={...answers,email:answers.email||undefined,serviceCondition:answers.serviceCondition||undefined,urgency:content.urgent?answers.serviceCondition:undefined,issueDetail:answers.issueDetail||undefined,notes:answers.notes||undefined,campaignId:campaign.id,offerName:campaign.offerLabel,campaignTag:content.tag,pageName:campaign.title,landingPageUrl:location.href,utmSource:params.get("utm_source")||undefined,utmMedium:params.get("utm_medium")||undefined,utmCampaign:params.get("utm_campaign")||undefined,utmContent:params.get("utm_content")||undefined,utmTerm:params.get("utm_term")||undefined,gclid:params.get("gclid")||undefined,fbclid:params.get("fbclid")||undefined,website:""};
    try{const response=await fetch("/api/campaign-leads",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify(payload)});const result=await response.json().catch(()=>({message:`The server returned an error (${response.status}).`}));if(!response.ok)throw new Error(result.message||"We could not send your request.");trackCampaignEvent("campaign_lead_submitted",campaign.id,{form_instance:instance,offer:campaign.offerLabel});location.assign(`/offers/${campaign.slug}/thank-you`)}catch(reason){const message=reason instanceof Error?reason.message:"Please call us or try again.";setError(message);trackCampaignEvent("campaign_form_error",campaign.id,{form_instance:instance,step})}finally{setBusy(false)}}
  const urgent=content.urgent&&(answers.serviceIssue==="Active Leak"||answers.serviceCondition.startsWith("Yes—"));
  return <form id={instance==="primary"?"appointment-form":undefined} onFocus={start} onSubmit={submit} className="mx-auto w-full max-w-2xl overflow-hidden rounded-3xl bg-white text-left shadow-2xl" noValidate data-campaign={campaign.id}>
    <input type="hidden" name="offerName" value={campaign.offerLabel}/><input type="hidden" name="campaignId" value={campaign.id}/><input type="hidden" name="campaignTag" value={content.tag}/>
    <div className="bg-navy px-5 py-4 text-white sm:px-7"><div className="flex items-center justify-between gap-3"><div><p className="text-xs font-black uppercase tracking-[.16em] text-copper-light">{campaign.offerLabel}</p><p className="mt-1 text-sm font-bold">Step {step} of 4</p></div><span className="text-xs text-slate-300">About 60 seconds</span></div><div className="mt-3 h-2 overflow-hidden rounded-full bg-white/15"><div className="h-full rounded-full bg-copper transition-[width] duration-300" style={{width:`${step*25}%`}}/></div></div>
    <div key={step} className="wizard-step p-5 sm:p-7">
      {step===1&&<><h2 className="text-2xl font-black text-navy sm:text-3xl">{content.stepOne}</h2><p className="mt-2 text-sm leading-6 text-slate-600">Tell us where we can reach you, and our team will follow up shortly.</p><div className="mt-6 grid gap-4 sm:grid-cols-2"><label className="text-sm font-bold text-navy" htmlFor={`${id}-first`}>First name *<input id={`${id}-first`} name="firstName" autoComplete="given-name" className={field} value={answers.firstName} onChange={e=>update("firstName",e.target.value)} maxLength={60}/></label><label className="text-sm font-bold text-navy" htmlFor={`${id}-last`}>Last name *<input id={`${id}-last`} name="lastName" autoComplete="family-name" className={field} value={answers.lastName} onChange={e=>update("lastName",e.target.value)} maxLength={60}/></label><label className="text-sm font-bold text-navy" htmlFor={`${id}-phone`}>Phone number *<input id={`${id}-phone`} name="phone" type="tel" inputMode="tel" autoComplete="tel" className={field} value={answers.phone} onChange={e=>update("phone",e.target.value)} maxLength={30}/></label><label className="text-sm font-bold text-navy" htmlFor={`${id}-email`}>Email address <span className="font-normal text-slate-500">(optional)</span><input id={`${id}-email`} name="email" type="email" inputMode="email" autoComplete="email" className={field} value={answers.email} onChange={e=>update("email",e.target.value)} maxLength={150}/></label></div></>}
      {step===2&&<><h2 className="text-2xl font-black text-navy sm:text-3xl">Tell us a little about the property.</h2><p className="mt-5 text-sm font-bold text-navy">Is this a residential or commercial property?</p><div className="mt-3 grid grid-cols-2 gap-3">{[{value:"Residential",label:"Residential",icon:Home},{value:"Commercial",label:"Commercial",icon:Building2}].map(item=><button key={item.value} type="button" onClick={()=>update("propertyType",item.value)} className={`grid min-h-28 place-items-center rounded-2xl border-2 p-3 font-black shadow-md transition ${answers.propertyType===item.value?"border-navy bg-copper text-navy ring-2 ring-copper/40":"border-navy-light bg-navy-light text-white hover:border-copper hover:bg-navy"}`}><item.icon className={`mb-2 size-8 ${answers.propertyType===item.value?"text-navy":"text-copper-light"}`}/>{item.label}</button>)}</div><p className="mt-6 text-sm font-bold text-navy">Where is the property located?</p><div className="mt-3 grid gap-4 sm:grid-cols-2"><label className="text-sm font-bold text-navy" htmlFor={`${id}-city`}>City *<input id={`${id}-city`} name="city" autoComplete="address-level2" className={field} value={answers.city} onChange={e=>update("city",e.target.value)} maxLength={80}/></label><label className="text-sm font-bold text-navy" htmlFor={`${id}-zip`}>ZIP code *<input id={`${id}-zip`} name="zipCode" inputMode="numeric" autoComplete="postal-code" className={field} value={answers.zipCode} onChange={e=>update("zipCode",e.target.value)} maxLength={10}/></label><label className="text-sm font-bold text-navy sm:col-span-2" htmlFor={`${id}-state`}>State<input id={`${id}-state`} name="state" className={`${field} bg-slate-100 font-semibold`} value={answers.state} readOnly/></label></div></>}
      {step===3&&<><h2 className="text-2xl font-black text-navy sm:text-3xl">{content.serviceHeading}</h2><div className="mt-5"><ChoiceCards name="Service needed" choices={content.issues} value={answers.serviceIssue} onChange={value=>update("serviceIssue",value)}/></div>{content.conditionHeading&&content.conditions&&<><p className="mt-6 text-sm font-black text-navy">{content.conditionHeading}</p><div className="mt-3"><ChoiceCards name={content.conditionHeading} choices={content.conditions} value={answers.serviceCondition} onChange={value=>update("serviceCondition",value)} columns={false}/></div></>}{(answers.serviceIssue==="Other Plumbing Repair"||answers.serviceIssue==="Other Plumbing Issue")&&<label className="mt-5 block text-sm font-bold text-navy" htmlFor={`${id}-detail`}>Briefly describe the issue <span className="font-normal text-slate-500">(optional)</span><input id={`${id}-detail`} name="issueDetail" className={field} value={answers.issueDetail} onChange={e=>update("issueDetail",e.target.value)} maxLength={500}/></label>}{urgent&&<div className="mt-5 rounded-2xl border-2 border-emergency bg-red-50 p-4 text-sm font-bold leading-6 text-red-800"><p>Need immediate help?</p><a className="mt-2 inline-flex items-center gap-2 text-base underline" href={campaignPhoneHref(campaign.phone)}><Phone className="size-4"/>Call CTA Plumbing 100 now at {campaignPhoneDisplay(campaign.phone)}</a></div>}</>}
      {step===4&&<><h2 className="text-2xl font-black text-navy sm:text-3xl">When is the best time for us to reach you?</h2><p className="mt-5 text-sm font-black text-navy">What is the best time to contact you?</p><div className="mt-3"><ChoiceCards name="Best contact time" choices={["Morning","Afternoon","Evening","Anytime"].map(label=>({value:label,label}))} value={answers.contactTime} onChange={value=>update("contactTime",value)}/></div><p className="mt-6 text-sm font-black text-navy">How would you prefer to be contacted?</p><div className="mt-3"><ChoiceCards name="Contact preference" choices={["Phone Call","Text Message","Email","No Preference"].map(label=>({value:label,label}))} value={answers.contactPreference} onChange={value=>update("contactPreference",value)}/></div><label className="mt-6 block text-sm font-bold text-navy" htmlFor={`${id}-notes`}>Anything else we should know? <span className="font-normal text-slate-500">(optional)</span><textarea id={`${id}-notes`} name="notes" rows={3} className={`${field} py-3`} placeholder={content.placeholder} value={answers.notes} onChange={e=>update("notes",e.target.value)} maxLength={1500}/></label><div className="mt-6 rounded-2xl bg-slate-50 p-4 text-sm leading-6"><p className="font-black text-navy">Review your request</p><p className="mt-2 text-slate-600"><strong>{campaign.offerLabel}</strong> · {answers.propertyType} · {answers.serviceIssue}</p><button type="button" onClick={()=>setStep(1)} className="mt-2 text-xs font-black text-copper-dark underline">Edit earlier answers</button></div><SmsConsentFields idPrefix={`${id}-${instance}`} className="mt-6" transactionalInputProps={{checked:answers.smsTransactionalConsent,onChange:e=>update("smsTransactionalConsent",e.currentTarget.checked)}} marketingInputProps={{checked:answers.smsMarketingConsent,onChange:e=>update("smsMarketingConsent",e.currentTarget.checked)}}/></>}
      {error&&<p role="alert" className="mt-5 rounded-xl bg-red-50 p-4 text-sm font-bold text-red-800">{error}</p>}
      <div className="mt-6 flex items-center gap-3">{step>1&&<button type="button" onClick={back} disabled={busy} className="inline-flex min-h-12 items-center gap-2 rounded-xl px-3 text-sm font-black text-slate-600 hover:bg-slate-100"><ArrowLeft className="size-4"/>Back</button>}<button type={step===4?"submit":"button"} onClick={step<4?next:undefined} disabled={busy} className="ml-auto inline-flex min-h-14 flex-1 items-center justify-center gap-2 rounded-xl bg-emergency px-5 font-black text-white shadow-lg transition hover:bg-red-700 disabled:opacity-60 sm:flex-none">{busy?<><LoaderCircle className="size-5 animate-spin"/>Sending Your Request…</>:step===4?content.submit:<>{"Continue"}<ArrowRight className="size-5"/></>}</button></div>
    </div>
  </form>
}
