import Image from "next/image";
import Link from "next/link";
import { ArrowRight, Check, MapPin, Phone } from "lucide-react";
import { services, locations } from "@/lib/content";
import { phoneHref, site } from "@/lib/site";
import { Button } from "@/components/ui/button";

export function Eyebrow({ children }: { children: React.ReactNode }) { return <p className="eyebrow">{children}</p>; }
export function SectionHeading({ eyebrow, title, text, center = false }: { eyebrow: string; title: string; text?: string; center?: boolean }) { return <div className={center ? "mx-auto mb-10 max-w-3xl text-center" : "mb-8 max-w-2xl"}><Eyebrow>{eyebrow}</Eyebrow><h2 className="section-title">{title}</h2>{text && <p className="section-copy">{text}</p>}</div>; }
export function Breadcrumbs({ items }: { items: { label: string; href?: string }[] }) { return <nav className="container py-4 text-sm text-slate-500" aria-label="Breadcrumb"><ol className="flex flex-wrap gap-2"><li><Link href="/">Home</Link></li>{items.map((item) => <li key={item.label} className="before:mr-2 before:content-['/']">{item.href ? <Link href={item.href}>{item.label}</Link> : <span aria-current="page">{item.label}</span>}</li>)}</ol></nav>; }
export function CallNow({ emergency: _emergency = false, label = "Call Now" }: { emergency?: boolean; label?: string }) { return <Button size="lg" variant="emergency" asChild><a href={phoneHref}><Phone />{label}</a></Button>; }
export function FinalCTA() { return <section className="bg-copper"><div className="container flex flex-col items-start justify-between gap-6 py-12 lg:flex-row lg:items-center"><div><p className="font-bold uppercase tracking-widest text-navy/70">Ready when you are</p><h2 className="mt-2 text-3xl font-black text-navy">Let’s get your plumbing request moving.</h2><p className="mt-2 text-navy/75">Call or send a request for service in Nampa and across the Treasure Valley.</p></div><div className="flex flex-wrap gap-3"><Button variant="navy" size="lg" asChild><Link href="/contact">Request Service</Link></Button><CallNow /></div></div></section>; }
export function EmergencyBar() { return <section className="bg-emergency text-white"><div className="container flex flex-col items-start justify-between gap-4 py-6 md:flex-row md:items-center"><div><h2 className="text-xl font-black">24/7 emergency plumbing help</h2><p className="mt-1 text-red-100">Call anytime for burst pipes, major leaks, backups, and other urgent plumbing problems.</p></div><CallNow emergency label="Call for Emergency Help" /></div></section>; }
export function ServiceGrid({ limit }: { limit?: number }) { const list = limit ? services.slice(0, limit) : services; return <div className="grid gap-5 sm:grid-cols-2 lg:grid-cols-3">{list.map((service) => <article className="card group" key={service.slug}><span className="icon-box"><Check /></span><h3 className="mt-5 text-xl font-black text-navy">{service.name}</h3><p className="mt-3 leading-7 text-slate-600">{service.short}</p><Link className="mt-5 inline-flex items-center gap-2 font-bold text-copper-dark" href={service.slug === "emergency-plumbing" ? "/emergency-plumbing" : `/services/${service.slug}`}>Explore service <ArrowRight className="size-4 transition-transform group-hover:translate-x-1" /></Link></article>)}</div>; }
export function LocationGrid() { return <div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-4">{locations.map((location) => <Link className="card flex items-center gap-3 hover:-translate-y-1 hover:border-copper" href={`/service-areas/${location.slug}`} key={location.slug}><MapPin className="text-copper-dark" /><span className="font-black text-navy">{location.city}</span></Link>)}</div>; }
export function SplitImage({ src, alt, children, reverse = false }: { src: string; alt: string; children: React.ReactNode; reverse?: boolean }) { return <div className="container grid items-center gap-10 lg:grid-cols-2"><div className={reverse ? "lg:order-2" : ""}>{children}</div><div className={`relative min-h-[420px] overflow-hidden rounded-3xl ${reverse ? "lg:order-1" : ""}`}><Image src={src} alt={alt} fill className="object-cover" sizes="(max-width: 1024px) 100vw, 50vw" /></div></div>; }
export function StickyMobileCall() { return <div className="fixed inset-x-4 bottom-4 z-40 md:hidden"><a href={phoneHref} className="flex min-h-14 items-center justify-center gap-2 rounded-xl bg-emergency px-5 font-black text-white shadow-2xl"><Phone />Call {site.phone}</a></div>; }
