import { randomUUID } from "node:crypto";
import { NextResponse } from "next/server";
import nodemailer from "nodemailer";
import { leadNotification } from "@/lib/lead-notification";
import { campaignLeadSchema, type CampaignLead } from "@/lib/campaign-lead-schema";
import { checkSubmissionSecurity, sanitizeObject } from "@/lib/form-security";
export const runtime="nodejs";
function env(name:string){const value=process.env[name]?.trim();if(!value)return undefined;return((value.startsWith('"')&&value.endsWith('"'))||(value.startsWith("'")&&value.endsWith("'")))?value.slice(1,-1).trim():value}
function sameOrigin(request:Request){const origin=request.headers.get("origin");if(!origin)return true;try{const host=request.headers.get("x-forwarded-host")?.split(",")[0]?.trim()||request.headers.get("host")?.trim();return Boolean(host&&new URL(origin).host.toLowerCase()===host.toLowerCase())}catch{return false}}
function safe(value:string|undefined){return value?.replace(/[\r\n]/g," ").slice(0,500)||"Not provided"}
function notification(lead: CampaignLead) {
  return leadNotification("New landing-page request", [
    { title: "Customer details", rows: [["Name", `${lead.firstName} ${lead.lastName}`], ["Phone", lead.phone], ["Email", lead.email], ["Property type", lead.propertyType], ["Location", `${lead.city}, ${lead.state} ${lead.zipCode}`], ["Preferred contact", lead.contactPreference], ["Best contact time", lead.contactTime]] },
    { title: "Service request", rows: [["Offer", lead.offerName], ["Service needed", lead.serviceIssue], ["Service follow-up", lead.serviceCondition], ["Urgency", lead.urgency], ["Issue details", lead.issueDetail], ["Additional notes", lead.notes]] },
    { title: "SMS consent", rows: [["Transactional messages", lead.smsTransactionalConsent ? "Yes" : "No"], ["Marketing messages", lead.smsMarketingConsent ? "Yes" : "No"]] },
    { title: "Advertising attribution", rows: [["Campaign", lead.campaignId], ["GHL tag", lead.campaignTag], ["Page", lead.pageName], ["Landing page", lead.landingPageUrl], ["UTM source", lead.utmSource], ["UTM medium", lead.utmMedium], ["UTM campaign", lead.utmCampaign], ["UTM content", lead.utmContent], ["UTM term", lead.utmTerm], ["Google click ID", lead.gclid], ["Meta click ID", lead.fbclid]] },
  ]);
}
async function sendGhl(lead:CampaignLead,requestId:string){const raw=env("GHL_WEBHOOK_URL");if(!raw)return{configured:false,delivered:false};let url:URL;try{url=new URL(raw);if(url.protocol!=="https:")throw new Error("HTTPS required")}catch{console.error(`[campaign-leads:${requestId}] ghl_webhook_invalid`);return{configured:true,delivered:false}}try{const response=await fetch(url,{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify(lead),signal:AbortSignal.timeout(10_000)});if(!response.ok)throw new Error(`HTTP ${response.status}`);console.info(`[campaign-leads:${requestId}] ghl_webhook_delivered`,{campaignId:lead.campaignId});return{configured:true,delivered:true}}catch(error){console.error(`[campaign-leads:${requestId}] ghl_webhook_failed`,{message:error instanceof Error?error.message.slice(0,200):"Unknown error"});return{configured:true,delivered:false}}}
export async function POST(request:Request){
  const requestId=randomUUID();console.info(`[campaign-leads:${requestId}] endpoint_received`,{contentType:request.headers.get("content-type")||"none"});if(!sameOrigin(request))return NextResponse.json({success:false,accepted:false,message:"This request is not allowed.",requestId},{status:403});if(Number(request.headers.get("content-length")||0)>40_000)return NextResponse.json({success:false,accepted:false,message:"The request is too large.",requestId},{status:413});
  let body:unknown;try{body=sanitizeObject(await request.json())}catch{return NextResponse.json({success:false,accepted:false,message:"The request could not be read.",requestId},{status:400})}const parsed=campaignLeadSchema.safeParse(body);if(!parsed.success){console.warn(`[campaign-leads:${requestId}] validation_failed`,{fields:Object.keys(parsed.error.flatten().fieldErrors)});return NextResponse.json({success:false,accepted:false,message:"Please complete every required field.",requestId},{status:400})}
  const lead=parsed.data;const security=await checkSubmissionSecurity({request,requestId,scope:"campaign-lead",honeypot:lead.website,formStartedAt:lead.formStartedAt,formSessionId:lead.formSessionId,turnstileToken:lead.turnstileToken,zipCode:lead.zipCode,requireServiceArea:false});if(!security.ok)return NextResponse.json({success:security.silent===true,accepted:false,code:security.code,message:security.message,requestId},{status:security.status});
  const ghl=await sendGhl(lead,requestId);const host=env("SMTP_HOST"),user=env("SMTP_USER"),password=env("SMTP_PASSWORD")?.replace(/\s+/g,""),from=env("SMTP_FROM"),recipient=env("LEAD_RECIPIENT"),cc=[env("EMAIL_CC") || "", "cadenctaplumbing100@gmail.com"].filter(Boolean);let emailDelivered=false;if(host&&user&&password&&from&&recipient){const port=Number(env("SMTP_PORT")||"465");try{const transporter=nodemailer.createTransport({host,port,secure:port===465||env("SMTP_SECURE")?.toLowerCase()==="true",auth:{user,pass:password}});await transporter.sendMail({from,to:recipient,cc,replyTo:lead.email,subject:`Campaign lead: ${lead.offerName}`,...notification(lead)});emailDelivered=true;console.info(`[campaign-leads:${requestId}] smtp_delivered`,{campaignId:lead.campaignId})}catch(error){const e=error as{code?:string;message?:string};let message=e.message||"Unknown SMTP error";for(const secret of[password,user])if(secret)message=message.split(secret).join("[redacted]");console.error(`[campaign-leads:${requestId}] smtp_delivery_failed`,{code:e.code||"UNKNOWN",message:message.slice(0,300)})}}
  if(ghl.delivered||emailDelivered)return NextResponse.json({success:true,accepted:true,message:"Thank you. Your request was sent. Our team will follow up soon.",requestId});if(process.env.NODE_ENV!=="production")return NextResponse.json({success:true,accepted:true,message:"Development mode: your request validated successfully.",requestId});console.error(`[campaign-leads:${requestId}] no_delivery_channel`,{ghlConfigured:ghl.configured});return NextResponse.json({success:false,accepted:false,message:"Online requests are temporarily unavailable. Please call us instead.",requestId},{status:503});
}
